<script setup lang="ts">
import { VerIcon, VerRow, VerCol } from 'versakit-ui'

const icons = [
  'passed',
  'pause-circle',
  'pause-circle-o',
  'phone-o',
  'pending-payment',
  'photograph',
  'phone-circle',
  'photo-fail',
  'phone',
  'photo',
  'plus',
  'photo-o',
  'play',
  'play-circle',
  'share',
  'point-gift',
  'points',
  'point-gift-o',
  'printer',
  'revoke',
  'search',
  'phone-circle-o',
  'send-gift-o',
  'scan',
  'send-gift',
  'qr',
  'play-circle-o',
  'stop-circle-o',
  'service-o',
  'qr-invalid',
  'question-o',
  'records',
  'setting',
  'setting-o',
  'shop-collect-o',
  'share-o',
  'replay',
  'question',
  'refund-o',
  'shopping-cart',
  'shop',
  'shopping-cart-o',
  'shop-collect',
  'sign',
  'shop-o',
  'smile-o',
  'smile-comment-o',
  'stop',
  'smile',
  'stop-circle',
  'success',
  'smile-comment',
  'tosend',
  'star-o',
  'todo-list',
  'sort',
  'underway',
  'tv-o',
  'umbrella-circle',
  'video',
  'vip-card',
  'service',
  'volume-o',
  'user-o',
  'wap-nav',
  'wap-home',
  'video-o',
  'wap-home-o',
  'weapp-nav',
  'underway-o',
  'warning',
  'vip-card-o',
  'volume',
  'user-circle-o',
  'warn-o',
  'warning-o',
  'wechat-pay',
  'shrink',
  'star',
  'youzan-shield',
  'thumb-circle',
  'todo-list-o',
  'thumb-circle-o',
  'wechat',
  'upgrade',
  'shield-o',
  'invitation',
  'guide-o',
  'add-square',
  'add',
  'add-o',
  'arrow-left',
  'aim',
  'arrow',
  'arrow-up',
  'arrow-down',
  'alipay',
  'ascending',
  'after-sale',
  'bag-o',
  'audio',
  'back-top',
  'award',
  'bag',
  'award-o',
  'balance-list',
  'balance-o',
  'bell',
  'bar-chart-o',
  'balance-list-o',
  'bars',
  'balance-pay',
  'birthday-cake-o',
  'bill-o',
  'bookmark',
  'bookmark-o',
  'browsing-history-o',
  'brush-o',
  'bill',
  'bullhorn-o',
  'bulb-o',
  'calendar-o',
  'card',
  'cart',
  'browsing-history',
  'cart-o',
  'chart-trending-o',
  'cash-back-record',
  'certificate',
  'cashier-o',
  'cash-on-deliver',
  'cart-circle-o',
  'chat',
  'clock',
  'circle',
  'cart-circle',
  'apps-o',
  'clear',
  'close',
  'checked',
  'comment-o',
  'comment-circle-o',
  'closed-eye',
  'clock-o',
  'cluster-o',
  'chat-o',
  'cluster',
  'column',
  'comment',
  'contact',
  'credit-pay',
  'coupon-o',
  'completed',
  'descending',
  'comment-circle',
  'cross',
  'diamond',
  'delete',
  'diamond-o',
  'envelop-o',
  'desktop-o',
  'ecard-pay',
  'edit',
  'coupon',
  'delete-o',
  'down',
  'ellipsis',
  'enlarge',
  'expand',
  'description',
  'exchange',
  'eye-o',
  'expand-o',
  'eye',
  'fail',
  'debit-pay',
  'discount',
  'filter-o',
  'failure',
  'fire',
  'font',
  'flag-o',
  'font-o',
  'fire-o',
  'free-postage',
  'friends-o',
  'gem-o',
  'gem',
  'friends',
  'gift',
  'gift-o',
  'gift-card-o',
  'good-job',
  'flower-o',
  'gold-coin-o',
  'gold-coin',
  'good-job-o',
  'home-o',
  'gift-card',
  'graphic',
  'hot-o',
  'idcard',
  'hot-sale-o',
  'info',
  'hot-sale',
  'hotel-o',
  'goods-collect-o',
  'info-o',
  'label-o',
  'hot',
  'label',
  'location-o',
  'goods-collect',
  'location',
  'lock',
  'like-o',
  'live',
  'manager-o',
  'like',
  'manager',
  'map-marked',
  'logistics',
  'more',
  'medal',
  'more-o',
  'music-o',
  'music',
  'newspaper-o',
  'minus',
  'new-o',
  'new-arrival',
  'notes-o',
  'orders-o',
  'medal-o',
  'new',
  'new-arrival-o',
  'other-pay',
  'pause',
  'peer-pay',
  'paid',
]
</script>

<template>
  <ver-row>
    <ver-col :span="4" v-for="(item, index) in icons" :key="index">
      <ul>
        <li>
          <ver-icon :name="item" size="30" />
          <span>{{ item }}</span>
        </li>
      </ul>
    </ver-col>
  </ver-row>
</template>

<style lang="scss" scoped>
.ver-col {
  margin: 10px 0px;
}

ul {
  display: flex;
  justify-content: space-around;
  list-style: none;
  flex-wrap: wrap;
  margin: 0;
  padding: 0;

  li {
    padding: 1rem;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;

    &:hover {
      color: skyblue;
    }

    span {
      margin: 0.25rem 0px;
    }
  }
}
</style>
